### ISSUE TITLE
Partial Sync data anomoly error

### ISSUE THREAD

**Issue by edrock200** [m-rots/bernard#15]
I keep getting this error on partial syncs:
` performing partial sync: ID does not exist from hook: datastore: data anomaly"`

If I delete the DB and do a full sync, it works. But all subsequent partial syncs still fail for some reason. I'm not really sure where to go from here.

**Comment by m-rots** [comment]
I will not explore data anomaly errors in Bernard Go going forward. Autoscan's A-Train trigger which is based on [`bernard-rs`](https://github.com/m-rots/bernard-rs) does not seem to suffer the same issue.
